#[path = "billing/billing_account_repository.rs"]
pub mod billing_account_repository;
#[path = "billing/company_repository.rs"]
pub mod company_repository;
#[path = "billing/folio_entry_repository.rs"]
pub mod folio_entry_repository;
#[path = "billing/folio_repository.rs"]
pub mod folio_repository;
#[path = "guest/guest_preference_repository.rs"]
pub mod guest_preference_repository;
#[path = "guest/guest_repository.rs"]
pub mod guest_repository;
#[path = "guest/guest_timeline_event_repository.rs"]
pub mod guest_timeline_event_repository;
#[path = "billing/invoice_repository.rs"]
pub mod invoice_repository;
#[path = "operation/operation_change_event_repository.rs"]
pub mod operation_change_event_repository;
#[path = "rate_plan/package_definition_repository.rs"]
pub mod package_definition_repository;
#[path = "billing/payment_allocation_repository.rs"]
pub mod payment_allocation_repository;
#[path = "billing/payment_repository.rs"]
pub mod payment_repository;
#[path = "billing/receivable_repository.rs"]
pub mod receivable_repository;
#[path = "reservation/reservation_daily_revenue_allocation_repository.rs"]
pub mod reservation_daily_revenue_allocation_repository;
#[path = "reservation/reservation_daily_stay_detail_repository.rs"]
pub mod reservation_daily_stay_detail_repository;
#[path = "reservation/reservation_guest_relation_repository.rs"]
pub mod reservation_guest_relation_repository;
#[path = "reservation/reservation_package_breakdown_repository.rs"]
pub mod reservation_package_breakdown_repository;
#[path = "reservation/reservation_repository.rs"]
pub mod reservation_repository;
#[path = "reservation/revenue_summary_repository.rs"]
pub mod revenue_summary_repository;
#[path = "room/room_daily_state_repository.rs"]
pub mod room_daily_state_repository;
#[path = "room/room_repository.rs"]
pub mod room_repository;
