CREATE TABLE IF NOT EXISTS daily_room_class_kpi_aggregates (
    service_date TEXT NOT NULL,
    room_class TEXT NOT NULL,
    total_rooms INTEGER NOT NULL,
    out_of_order_rooms INTEGER NOT NULL,
    reservable_rooms INTEGER NOT NULL,
    sold_room_nights INTEGER NOT NULL,
    occupied_rooms INTEGER NOT NULL,
    room_revenue TEXT NOT NULL,
    food_and_beverage_revenue TEXT NOT NULL,
    other_revenue TEXT NOT NULL,
    tax_amount TEXT NOT NULL,
    total_revenue TEXT NOT NULL,
    occupancy_rate TEXT NOT NULL,
    adr TEXT NOT NULL,
    revpar TEXT NOT NULL,
    projection_version INTEGER NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (service_date, room_class)
);
